// The caste picklist the legacy Committee Management screen (cadreCommittee.txt /
// committessBlockSection.js) hard-codes client-side rather than fetching — there is no
// migrated PSA endpoint for it (the old getCastesByCasteCategoryId.action /
// getAllCasteDetailsForVotersAction.action calls were never ported), so this is copied
// verbatim from that legacy array rather than guessed at. Used to assign a `casteId` to a
// staged KSS member before saveSection/addKSSMember, which both require one.
export const CASTE_LIST = [
  { id: 228, name: 'Aandh' }, { id: 326, name: 'AASADULA' }, { id: 75, name: 'Achukuntla Vandlu' },
  { id: 312, name: 'Adi Dravida' }, { id: 224, name: 'AdiAndhra' }, { id: 461, name: 'Agamudayar' },
  { id: 309, name: 'Agamudi Mudaliar' }, { id: 121, name: 'Agaru' }, { id: 1, name: 'Agnikula kshathriya' },
  { id: 199, name: 'Anamakh' }, { id: 200, name: 'Andhravida' }, { id: 122, name: 'Arae' },
  { id: 388, name: 'Arakalies and Surabi natakalavallu' }, { id: 201, name: 'Arapamala' }, { id: 347, name: 'Arava' },
  { id: 387, name: 'Are Marathi' }, { id: 123, name: 'Arekatika' }, { id: 202, name: 'Aremala' },
  { id: 177, name: 'Arundatheeya' }, { id: 329, name: 'Arwa Mala' }, { id: 76, name: 'Arya Kshathrya' },
  { id: 124, name: 'Atagara' }, { id: 397, name: 'Atirasa' }, { id: 77, name: 'Avusala' },
  { id: 396, name: 'Ayyaraka' }, { id: 2, name: 'Badar' }, { id: 229, name: 'Bagatha' },
  { id: 3, name: 'Balasanthu' }, { id: 296, name: 'Balija' }, { id: 467, name: 'Balija Kapu' },
  { id: 4, name: 'Banda' }, { id: 5, name: 'Bandara' }, { id: 353, name: 'Banjara' },
  { id: 230, name: 'Barhika Duliya' }, { id: 203, name: 'Barigi' }, { id: 125, name: 'Batraju' },
  { id: 162, name: 'Bavuri' }, { id: 120, name: 'BC - C (Cristians)' }, { id: 178, name: 'Bedajangam' },
  { id: 204, name: 'Begara' }, { id: 442, name: 'Behar' }, { id: 179, name: 'Bendla' },
  { id: 449, name: 'Bengali' }, { id: 342, name: 'Beri Sheety' }, { id: 6, name: 'Bestha' },
  { id: 391, name: 'Bhadbhunja' }, { id: 7, name: 'Bhahurupi' }, { id: 390, name: 'Bhunjwa' },
  { id: 8, name: 'Bikshaka Vruthi' }, { id: 439, name: 'Biksham Gunta' }, { id: 231, name: 'Bil' },
  { id: 403, name: 'Bindla' }, { id: 331, name: 'Binedu' }, { id: 416, name: 'Bodo Gadaba' },
  { id: 306, name: 'Bondili' }, { id: 293, name: 'Boya' }, { id: 284, name: 'Brahmin' },
  { id: 9, name: 'Buda Bukkala' }, { id: 180, name: 'Budaga Jangam' }, { id: 389, name: 'Budubunjala' },
  { id: 126, name: 'Bukka' }, { id: 354, name: 'Bukka Ayyavara' }, { id: 404, name: 'Byagara' },
  { id: 405, name: 'Chachati' }, { id: 444, name: 'Chacherlu' }, { id: 406, name: 'Chalavadi' },
  { id: 205, name: 'Challavadi' }, { id: 181, name: 'Chamar' }, { id: 182, name: 'Chambar' },
  { id: 410, name: 'Chanchandi' }, { id: 164, name: 'Chandala' }, { id: 163, name: 'Chavati' },
  { id: 232, name: 'Chenchu Varu' }, { id: 233, name: 'Chenchumuni' }, { id: 127, name: 'Chimpollu' },
  { id: 78, name: 'Chithari' }, { id: 79, name: 'Chithrakara' }, { id: 445, name: 'Chitti Karanam' },
  { id: 11, name: 'Chopamali' }, { id: 459, name: 'Christian' }, { id: 470, name: 'Converted Harijans' },
  { id: 183, name: 'Dakkal/Dakkala Varu' }, { id: 355, name: 'Damala' }, { id: 165, name: 'Dandasi' },
  { id: 12, name: 'Dasari (BC-A)' }, { id: 128, name: 'Dasari (BC-D)' }, { id: 234, name: 'Deseeya kondulu' },
  { id: 235, name: 'Desiya Dondulu' }, { id: 80, name: 'Devanga' }, { id: 13, name: 'Devara Vandlu' },
  { id: 184, name: 'Dhor' }, { id: 423, name: 'Dhulia' }, { id: 167, name: 'DomDombara' },
  { id: 14, name: 'Dommara' }, { id: 236, name: 'Dondra Kodulu' }, { id: 81, name: 'Dudekula' },
  { id: 82, name: 'Ediga' }, { id: 321, name: 'EKILA' }, { id: 352, name: 'Ekiri' },
  { id: 15, name: 'Ellamma Vandlu' }, { id: 16, name: 'Ellasi' }, { id: 345, name: 'Erla' },
  { id: 237, name: 'Gadabalu' }, { id: 415, name: 'Gadabas' }, { id: 129, name: 'Gadava' },
  { id: 318, name: 'Gajula Balija' }, { id: 83, name: 'Gamalla Kalali' }, { id: 84, name: 'Gandla' },
  { id: 18, name: 'Ganga Varu' }, { id: 17, name: 'Gangaputhra' }, { id: 19, name: 'Gangireddu Varu' },
  { id: 340, name: 'Ganuga Sheety' }, { id: 168, name: 'Gasi' }, { id: 130, name: 'Gavara' },
  { id: 407, name: 'Ghasi' }, { id: 131, name: 'Ginghar' }, { id: 85, name: 'Giniyar' },
  { id: 170, name: 'Godagali' }, { id: 185, name: 'Godari' }, { id: 20, name: 'Gondlu' },
  { id: 238, name: 'Gondu' }, { id: 206, name: 'Gosam' }, { id: 411, name: 'Gosangi' },
  { id: 357, name: 'Gotrala' }, { id: 239, name: 'Goud-ST' }, { id: 86, name: 'Gouda' },
  { id: 240, name: 'Goudh' }, { id: 87, name: 'Goundla' }, { id: 21, name: 'Gudala' },
  { id: 392, name: 'Gudia' }, { id: 393, name: 'Gudiya' }, { id: 417, name: 'Gutob Gadaba' },
  { id: 408, name: 'Haddi' }, { id: 169, name: 'Haddi (or) Relli chachandi' }, { id: 446, name: 'Harijans' },
  { id: 132, name: 'Hatkhar' }, { id: 419, name: 'Hill Reddis' }, { id: 207, name: 'Huleya' },
  { id: 208, name: 'Huleya Dasari' }, { id: 186, name: 'Jaggali' }, { id: 412, name: 'JaJnbllvulu' },
  { id: 332, name: 'Jakkula' }, { id: 22, name: 'Jalari' }, { id: 187, name: 'Jambavulu' },
  { id: 88, name: 'Jandra' }, { id: 23, name: 'Jangam' }, { id: 241, name: 'Jathapass' },
  { id: 24, name: 'Jogi' }, { id: 341, name: 'Jogula' }, { id: 25, name: 'Joshinandala Bala' },
  { id: 133, name: 'Kachi' }, { id: 26, name: 'Kaikadi' }, { id: 89, name: 'Kaikala' },
  { id: 438, name: 'Kaitha Lambadi(Labhana)' }, { id: 134, name: 'Kakkana' }, { id: 335, name: 'Kalai Balija' },
  { id: 135, name: 'Kalavanthulu Ganika' }, { id: 324, name: 'KALINGA' }, { id: 440, name: 'Kalinga Vysya' },
  { id: 418, name: 'kallayi gadaba' }, { id: 27, name: 'Kalli Kapu' }, { id: 290, name: 'Kamma' },
  { id: 90, name: 'Kammara (BC)' }, { id: 242, name: 'Kammara (ST)' }, { id: 91, name: 'Kamsali/Vishva Bramhana' },
  { id: 92, name: 'Kanchra' }, { id: 136, name: 'Kandhra' }, { id: 28, name: 'Kanjara Battu' },
  { id: 288, name: 'Kapu' }, { id: 466, name: 'Kapu Kapu' }, { id: 469, name: 'Kapu-ST' },
  { id: 304, name: 'KARANAM' }, { id: 323, name: 'KARIKALABHAKTHULA' }, { id: 93, name: 'Karna Bakthulu' },
  { id: 322, name: 'KARNABHAKTHULA' }, { id: 358, name: 'Kasikapadi' }, { id: 94, name: 'Kathri' },
  { id: 29, name: 'Kati Papala' }, { id: 243, name: 'Katunaikan' }, { id: 333, name: 'Kavali' },
  { id: 431, name: 'Kerala' }, { id: 359, name: 'Keuta' }, { id: 360, name: 'Keviti' },
  { id: 361, name: 'Kevuto' }, { id: 30, name: 'Kinthala Kalinga' }, { id: 31, name: 'Kirathaka' },
  { id: 244, name: 'Kodhu' }, { id: 245, name: 'Kodi' }, { id: 420, name: 'Kolam' },
  { id: 421, name: 'Kolawar' }, { id: 188, name: 'Koluvula Vandlu' }, { id: 32, name: 'Kompara/Reddika' },
  { id: 246, name: 'Konda Doralu' }, { id: 247, name: 'Konda Kapulu' }, { id: 248, name: 'Konda Reddlu' },
  { id: 250, name: 'Kondlu' }, { id: 137, name: 'Koppula Velama' }, { id: 251, name: 'Koputiya' },
  { id: 252, name: 'Koram' }, { id: 33, name: 'Korcha' }, { id: 138, name: 'Kosti' },
  { id: 433, name: 'Kotiya' }, { id: 253, name: 'Kotiya Benthu' }, { id: 254, name: 'Koya' },
  { id: 139, name: 'Krushna Balija' }, { id: 34, name: 'Kshathriya (BC)' }, { id: 291, name: 'Kshatriya (OC)' },
  { id: 255, name: 'Kuliya' }, { id: 256, name: 'Kulwalapai' }, { id: 95, name: 'Kummara' },
  { id: 35, name: 'Kunapuli' }, { id: 429, name: 'Kunkuma' }, { id: 475, name: 'Kuraba' },
  { id: 362, name: 'Kurakala' }, { id: 382, name: 'Kurni' }, { id: 96, name: 'Kuruma' },
  { id: 257, name: 'Kuttiya Kodulu' }, { id: 317, name: 'Labbai' }, { id: 97, name: 'Laddaf' },
  { id: 402, name: 'Lakkamari Kapu' }, { id: 363, name: 'Lambada' }, { id: 258, name: 'Lambadi' },
  { id: 313, name: 'Lingayat' }, { id: 384, name: 'Lodh' }, { id: 386, name: 'Lodha' },
  { id: 385, name: 'Lodhi' }, { id: 189, name: 'Madiga' }, { id: 190, name: 'Madiga Dasu' },
  { id: 209, name: 'Madisi Kuruva/Madaari Kuruva' }, { id: 210, name: 'Mahar' }, { id: 36, name: 'Mahathar' },
  { id: 211, name: 'Mala' }, { id: 212, name: 'Mala Dasari' }, { id: 213, name: 'Mala Hannai' },
  { id: 214, name: 'Mala Jangam' }, { id: 216, name: 'Mala Masthi' }, { id: 217, name: 'Mala Sala' },
  { id: 218, name: 'Mala sanyasi' }, { id: 427, name: 'Maladasu' }, { id: 140, name: 'Mali' },
  { id: 259, name: 'Malin' }, { id: 37, name: 'Mandala (BC)' }, { id: 219, name: 'Mandala (SC)' },
  { id: 364, name: 'Mandula' }, { id: 191, name: 'Mang Garodi' }, { id: 192, name: 'Manga' },
  { id: 260, name: 'Manna Dora' }, { id: 220, name: 'Manne' }, { id: 448, name: 'Mannepu' },
  { id: 261, name: 'Mannevaru' }, { id: 315, name: 'MARATI' }, { id: 330, name: 'MARWADI' },
  { id: 225, name: 'Masthi' }, { id: 193, name: 'Masthima' }, { id: 194, name: 'Mathangi' },
  { id: 262, name: 'Mathaya Vavaras (or) Kuttu Vavaras' }, { id: 141, name: 'Mathula' }, { id: 305, name: 'MAYDARA' },
  { id: 39, name: 'Medari' }, { id: 171, name: 'Mehthar' }, { id: 319, name: 'Mera Darji' },
  { id: 226, name: 'Mitha Iyala Varu' }, { id: 195, name: 'Mochi' }, { id: 301, name: 'Mohamad' },
  { id: 40, name: 'Mondi Banda' }, { id: 41, name: 'Mondi Varu' }, { id: 42, name: 'Mondipatta' },
  { id: 196, name: 'Moochi' }, { id: 98, name: 'Muchi' }, { id: 460, name: 'Mudaliar' },
  { id: 143, name: 'Mudhiraj' }, { id: 263, name: 'Muka Dora' }, { id: 314, name: 'MUNDALA' },
  { id: 144, name: 'Munnoor Kapu' }, { id: 292, name: 'Muslim' }, { id: 145, name: 'Mutharasi' },
  { id: 43, name: 'Muthyalamma Vandlu' }, { id: 428, name: 'Myralu' }, { id: 451, name: 'N/A' },
  { id: 348, name: 'Nadar' }, { id: 435, name: 'Nagaralu' }, { id: 99, name: 'Nagavaddilu' },
  { id: 146, name: 'Nagavamsha' }, { id: 147, name: 'Nagavasam' }, { id: 264, name: 'Naik' },
  { id: 265, name: 'Naikpoth' }, { id: 100, name: 'Nakhan' }, { id: 44, name: 'Nakkala' },
  { id: 349, name: 'Nambi' }, { id: 45, name: 'Nashadi' }, { id: 101, name: 'Nashni/Kurni' },
  { id: 307, name: 'Natari' }, { id: 426, name: 'Nayaka' }, { id: 344, name: 'Nayani Varu' },
  { id: 365, name: 'Nayanivaru' }, { id: 38, name: 'Nayee Brahmin' }, { id: 47, name: 'Nayyala' },
  { id: 102, name: 'Neelikanti' }, { id: 148, name: 'Nelli' }, { id: 325, name: 'NEPALI' },
  { id: 48, name: 'Nera Pravruthi Kalavaru' }, { id: 49, name: 'Nershakari' }, { id: 381, name: 'Nessi' },
  { id: 447, name: 'Nethekani' }, { id: 50, name: 'Nokkara' }, { id: 432, name: 'Nooka Dora' },
  { id: 298, name: 'Oreganti Reddy' }, { id: 458, name: 'OTHERS' }, { id: 472, name: 'OTHERS-BC' },
  { id: 471, name: 'OTHERS-OC' }, { id: 473, name: 'OTHERS-SC' }, { id: 474, name: 'OTHERS-ST' },
  { id: 103, name: 'Padmashali' }, { id: 166, name: 'Paidi/pano' }, { id: 424, name: 'Paiko' },
  { id: 172, name: 'Paki (or) Mothi' }, { id: 366, name: 'Pala Ekari' }, { id: 367, name: 'Palegaru' },
  { id: 300, name: 'Pallepu Kapu' }, { id: 310, name: 'Palli' }, { id: 343, name: 'Palli Kapu' },
  { id: 346, name: 'Palli Reddy' }, { id: 51, name: 'Pambala' }, { id: 174, name: 'Pamidi' },
  { id: 52, name: 'Pamula' }, { id: 227, name: 'Panchama (or) Pariyuhi' }, { id: 450, name: 'Panda' },
  { id: 150, name: 'Panjari' }, { id: 53, name: 'Pannari' }, { id: 266, name: 'Parangi Parcha' },
  { id: 422, name: 'Pardhan' }, { id: 54, name: 'Parthi' }, { id: 151, name: 'Paspi' },
  { id: 395, name: 'Passi' }, { id: 303, name: 'Pathan' }, { id: 104, name: 'Patkhar' },
  { id: 55, name: 'Patlavu' }, { id: 436, name: 'Patnayak' }, { id: 434, name: 'Patnayak' },
  { id: 316, name: 'PATRA' }, { id: 299, name: 'Pattapu' }, { id: 454, name: 'Pattusali' },
  { id: 56, name: 'Peddaboya' }, { id: 57, name: 'Peddama Vandlu' }, { id: 105, name: 'Perika' },
  { id: 106, name: 'Perika Balija' }, { id: 107, name: 'Pinjari/Noorbash' }, { id: 59, name: 'Piriki Muggula' },
  { id: 58, name: 'Pitchiguntla' }, { id: 152, name: 'Polinati Velama' }, { id: 368, name: 'Pondara' },
  { id: 153, name: 'Poosala' }, { id: 369, name: 'Poosala' }, { id: 267, name: 'Porja' },
  { id: 60, name: 'Porvam Bikshaka Vruthi' }, { id: 462, name: 'Pusala' }, { id: 425, name: 'Putiya' },
  { id: 61, name: 'Rajaka' }, { id: 370, name: 'Rajannala' }, { id: 334, name: 'Rajput' },
  { id: 289, name: 'Raju' }, { id: 268, name: 'Rajugondu' }, { id: 154, name: 'Rangaraju/Bhavasara Kshatriya' },
  { id: 441, name: 'Ravula' }, { id: 476, name: 'Reddika' }, { id: 285, name: 'Reddy' },
  { id: 269, name: 'Reddy Dora' }, { id: 465, name: 'Reddy Kapu' }, { id: 468, name: 'Reddy Reddy' },
  { id: 175, name: 'Relli' }, { id: 270, name: 'Rona Rena' }, { id: 443, name: 'Sabeerlu' },
  { id: 452, name: 'Sadara' }, { id: 155, name: 'Sadushetti' }, { id: 371, name: 'Saikalgar' },
  { id: 108, name: 'Sakulasali' }, { id: 197, name: 'Samagara' }, { id: 372, name: 'Samanthula' },
  { id: 221, name: 'Samband' }, { id: 222, name: 'Sambas' }, { id: 271, name: 'Sandrona' },
  { id: 109, name: 'Sangundam' }, { id: 176, name: 'Sapru' }, { id: 272, name: 'Sardhan' },
  { id: 156, name: 'Sathani' }, { id: 273, name: 'Savaras Kapusavaras' }, { id: 311, name: 'Seervi' },
  { id: 110, name: 'Settibalija' }, { id: 111, name: 'Shilpi' }, { id: 373, name: 'Siddula' },
  { id: 274, name: 'Sidopaiko' }, { id: 430, name: 'Sikh' }, { id: 374, name: 'Sikligar' },
  { id: 383, name: 'Silpis viswakarma' }, { id: 198, name: 'Sindollu' }, { id: 351, name: 'Singh' },
  { id: 401, name: 'Sistakaranam' }, { id: 398, name: 'sondi' }, { id: 375, name: 'Sountia' },
  { id: 112, name: 'Sri Sayan' }, { id: 275, name: 'Sugaleelu' }, { id: 399, name: 'sundi' },
  { id: 394, name: 'Surya Balija' }, { id: 339, name: 'Suryavamsha Rajulu' }, { id: 302, name: 'Syed' },
  { id: 328, name: 'Telaga' }, { id: 350, name: 'Telikula' }, { id: 113, name: 'Telugu Matlade Varu' },
  { id: 114, name: 'Thalikula' }, { id: 157, name: 'Thammali' }, { id: 158, name: 'Thenugollu' },
  { id: 276, name: 'Thikakariya Kodulu' }, { id: 115, name: 'Thogati Thogata' }, { id: 173, name: 'Thoti (BC)' },
  { id: 277, name: 'Thoti (ST)' }, { id: 159, name: 'Thurapu Kapu/Gajula Kapu' }, { id: 376, name: 'Tolagari' },
  { id: 160, name: 'Uppara/Sankara' }, { id: 338, name: 'Uppu vadde' }, { id: 377, name: 'Vadabalija' },
  { id: 283, name: 'Vaddera' }, { id: 62, name: 'Vaddi' }, { id: 63, name: 'Vaddolu' },
  { id: 116, name: 'Vadla' }, { id: 117, name: 'Vadra' }, { id: 118, name: 'Vadrangi' },
  { id: 64, name: 'Valli' }, { id: 65, name: 'Valli Reddy' }, { id: 414, name: 'Valluvan' },
  { id: 278, name: 'Valmiki' }, { id: 378, name: 'Valmiki' }, { id: 66, name: 'Valmiki Boya' },
  { id: 455, name: 'Vamsharaj' }, { id: 437, name: 'Vanjari' }, { id: 67, name: 'Vanne Kapu' },
  { id: 68, name: 'Vanne Reddy' }, { id: 336, name: 'Vannekapu' }, { id: 308, name: 'Vanyakulakshatriya' },
  { id: 400, name: 'varala' }, { id: 69, name: 'Vatti Kothala' }, { id: 70, name: 'Vedabaliga' },
  { id: 379, name: 'Veerabhadreeya' }, { id: 327, name: 'Veerashaiva LingayatLingabalija' }, { id: 287, name: 'Velama' },
  { id: 71, name: 'Venka Kula' }, { id: 72, name: 'Vera Musti' }, { id: 73, name: 'Vodde Yeddelu' },
  { id: 453, name: 'Vokkaliga' }, { id: 279, name: 'Voriya/bentu Voriya' }, { id: 380, name: 'Vyakula' },
  { id: 286, name: 'Vysya' }, { id: 161, name: 'Yadava' }, { id: 337, name: 'Yalam Reddy' },
  { id: 74, name: 'Yata' }, { id: 413, name: 'Yatala' }, { id: 223, name: 'Yellimal Varu' },
  { id: 280, name: 'Yenadi' }, { id: 281, name: 'Yerukala' }, { id: 282, name: 'Yoniti Kodulu' },
]
